# Generated by Django 4.1.2 on 2024-06-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePortafolio', models.CharField(max_length=100)),
                ('fechaIni', models.DateField()),
                ('infoPorta', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('soy', models.CharField(max_length=700)),
            ],
        ),
        migrations.AlterField(
            model_name='navbarmenu',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='navbarmenu',
            name='url',
            field=models.CharField(max_length=20),
        ),
    ]
