# Generated by Django 4.1.2 on 2024-06-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_portafolio_staff_alter_navbarmenu_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreServicio', models.CharField(max_length=100)),
                ('infoserv', models.CharField(max_length=700)),
            ],
        ),
    ]
