# Generated by Django 4.1.2 on 2024-07-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='mi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
