# Generated by Django 4.1.2 on 2024-07-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_staff_mi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='mi',
        ),
        migrations.AddField(
            model_name='staff',
            name='foto',
            field=models.ImageField(default='default.png', upload_to='static/images/'),
        ),
    ]
