# Generated by Django 4.1.2 on 2024-07-01 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_genero_alumno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='servicios',
            new_name='servicio',
        ),
    ]
